dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check certbot_install/certbot_install.yml"
  - "sudo ansible-playbook -i inventory/hosts.example certbot_install/certbot_install.yml"
